### ISSUE TITLE
problem in compiling the code using 'ant all'

### ISSUE THREAD

**Issue by abhisek-Chakrabarty** [karthikncode/MorphoChain#1]
I have downloaded the code of MorphoChain. When I am trying to compile using the command 'ant all' in ubuntu terminal, the following error occurs.

BUILD FAILED
.../module_morphology.xml:89: .../tools/lbfgsb_wrapper-1.1.2-src does not exist.

**Comment by karthikncode** [comment]
Hi Abhisek,
The path to the lbfgsb library was incorrect. I've fixed the build file - it should work now. Please try compiling and let me know.
Also, if you install your own copy of liblbfgsb, make sure to change the path accordingly in build.xml.

**Comment by abhisek-Chakrabarty** [comment]
Hi Karthik,
The path to the lbfgsb library is fixed in the build file but the corresponding changes in module_morphology.xml are not set resulting error in compilation.
However, I have changed the path to lbfgsb library in the module_morphology.xml file in my machine but still the following error occurs.

BUILD FAILED
.../module_morphology.xml:89: .../lib/lbfgsb_wrapper-1.1.2-src does not exist.

I checked the 'lbfgsb_wrapper-1.1.2.jar' in lib/ directory and found that it does contain 'src'. It does not contain 'raw_wrapper' also which is required.
So, if you upload the correct version of 'lbfgsb_wrapper-1.1.2.jar', then it will be helpful.

**Comment by karthikncode** [comment]
I see. The path for the source was incorrect. Fixed it now.

**Comment by karthikncode** [comment]
@abhisek-Chakrabarty Could you compile it now? Let me know and I can close the issue.

**Comment by abhisek-Chakrabarty** [comment]
Still, there are two problems in compilation. They are
1. the path for jdk.home.1.7 in the build.properties file is currently a particular machine specific. I think it should be set by the user.
2. The package junit.framework is not available.

**Comment by karthikncode** [comment]
Could you try setting the path to your local jdk? Also, try installing Junit using Maven and see if it compiles. Another way you can do this easily is to just import it in IntelliJ or Eclipse (if you use either of these IDEs) and compile.
